### ISSUE TITLE
Issues with QuickStart

### ISSUE THREAD

**Issue by AntoineDao** [hypar-io/function#5]
Wanted to take this for a quick spin and have been having issues with it unfortunately. Followed instructions [here](https://hypar-io.github.io/Elements/Functions/GetStartedWithFunctions.html) and am stuck when trying to create a new function.

I'll pre-empt that with the fact that I'm not a dotnet developer but I do fare well with Python, NodeJs and Golang. I have also roamed around the internet for this framework mismatch error and I'm not sure how to resolve it. Apologies in advance if I'm doing something really daft here :smile: 

I tried this on MacOs and then on a Ubuntu machine. Here's the output of the `dotnet --info` on ubuntu:
```console
~/ dotnet --info

.NET Core SDK (reflecting any global.json):
 Version:   2.2.300
 Commit:    73efd5bd87

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.300/

Host (useful for support):
  Version: 2.2.5
  Commit:  0a3c9209c0

.NET Core SDKs installed:
  2.1.700 [/usr/share/dotnet/sdk]
  2.2.300 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
I then install hypar without any problems:
> dotnet tool install -g hypar.cli

But generating the actual project fails:
```console
~/ hypar new -n MyFunction
Creating project MyFunction...
Error: Invalid parameter(s):
-f netcoreapp2.1
    'netcoreapp2.1' is not a valid value for -f (Framework).
Creating solution file...
Could not find project or directory `./src/MyFunction.csproj`.
There was an error adding the project to the solution.
   at Hypar.Commands.NewCommand.CreateProject(String functionName) in /home/mattdavidcampbell/hypar/Hypar/CLI/src/Commands/NewCommand.cs:line 175
   at Hypar.Commands.NewCommand.Execute(String name, FileInfo functionsProject, Boolean noPublish) in /home/mattdavidcampbell/hypar/Hypar/CLI/src/Commands/NewCommand.cs:line 75
The creation of a new function failed.
The directory, ./MyFunction, has been removed.
```
What am I doing wrong?

Also... Who is Matt David Campbell who appears in `/home/mattdavidcampbell/hypar/Hypar/CLI/src/Commands/...`?? I'm assuming it's not the same person who wrote [The House of Eros](https://www.amazon.com/House-Eros-Matthew-David-Campbell/dp/0692567844)? If so... I have so many questions.

**Comment by AntoineDao** [comment]
Oh boy I'm really gonna bother you guys with this one too. Can't get this repo to build either :see_no_evil: I cloned the repo and ran the following commands to no avail:
```console
 ~/dotnet restore

  Restore completed in 43.4 ms for /home/antoinedao/learning/dotnet/hypar/function/test/function-tests.csproj.
  Restore completed in 42.25 ms for /home/antoinedao/learning/dotnet/hypar/function/src/function.csproj.
  Restore completed in 50.45 ms for /home/antoinedao/learning/dotnet/hypar/function/test/function-tests.csproj.
```

And then tried to build it:
```console
~/ dotnet build                               

Welcome to .NET Core!
---------------------
Learn more about .NET Core: https://aka.ms/dotnet-docs
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs

Telemetry
---------
The .NET Core tools collect usage data in order to help us improve your experience. The data is anonymous and doesn't include command-line arguments. The data is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

ASP.NET Core
------------
Successfully installed the ASP.NET Core HTTPS Development Certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only). For establishing trust on other platforms refer to the platform specific documentation.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
Microsoft (R) Build Engine version 16.1.76+g14b0a930a7 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 23.85 ms for /home/antoinedao/learning/dotnet/hypar/function/test/function-tests.csproj.
  Restore completed in 22.52 ms for /home/antoinedao/learning/dotnet/hypar/function/src/function.csproj.
  Restore completed in 390.65 ms for /home/antoinedao/learning/dotnet/hypar/function/test/function-tests.csproj.
HyparDotnetStarter.cs(13,25): error CS0246: The type or namespace name 'Input' could not be found (are you missing a using directive or an assembly reference?) [/home/antoinedao/learning/dotnet/hypar/function/src/function.csproj]
HyparDotnetStarter.cs(13,10): error CS0246: The type or namespace name 'Output' could not be found (are you missing a using directive or an assembly reference?) [/home/antoinedao/learning/dotnet/hypar/function/src/function.csproj]

Build FAILED.

HyparDotnetStarter.cs(13,25): error CS0246: The type or namespace name 'Input' could not be found (are you missing a using directive or an assembly reference?) [/home/antoinedao/learning/dotnet/hypar/function/src/function.csproj]
HyparDotnetStarter.cs(13,10): error CS0246: The type or namespace name 'Output' could not be found (are you missing a using directive or an assembly reference?) [/home/antoinedao/learning/dotnet/hypar/function/src/function.csproj]
    0 Warning(s)
    2 Error(s)

Time Elapsed 00:00:02.78
```

Again... I'm sure I'm doing something silly here. Mind this is still on the ubuntu machine from above.

**Comment by ikeough** [comment]
@AntoineDao So sorry for the delayed reply. I am about to retire this repo because it is out of date. The updated recommendation will be to use the Hypar CLI, which now contains all the functionality required to bootstrap and publish a new function. It's a NuGet package that you can get by doing `dotnet tool install -g Hypar.CLI` from your favorite command line (provided you have .net core 2.1) installed. There will be better instructions posted here: https://hypar-io.github.io/Elements/Functions/GetStartedWithFunctions.html, when I get the time. In the mean time, I'm happy to help you get up and running.

**Comment by AntoineDao** [comment]
Man I'm a complete fool! I was using dotnet core 2.2... If anyone has similar issues, top tip is to add a `global.json` file with the correct version in the root of the directory where you work with Hypar stuff. Being a total noob at dotnet: [this helped](https://markheath.net/post/switching-between-netcore-sdk-versions). I'm making good progress now and hitting another wall which I will report here but try to resolve myself. Running `hypar new -n XXX` crashes on build of the default function (for linux):
```console
~/ hypar new -n testfunction
Creating project Testfunction...
Creating solution file...
Creating test project Testfunction.tests...
Adding tests to project...
Creating hypar.json...
Running hypar init...
Adding Hypar.Functions...
Adding Hypar.Elements...
Restoring Hypar dependencies...
Publishing private demo to Hypar...
Please provide your Hypar.io credentials, or sign up at https://hypar.io
Enter your Hypar.io user name:
antoinedao
Enter your Hypar.io password:
*************
Login to hypar for antoinedao was successful.

 ___  ___      ___    ___ ________  ________  ________     
|\  \|\  \    |\  \  /  /|\   __  \|\   __  \|\   __  \    
\ \  \\\  \   \ \  \/  / | \  \|\  \ \  \|\  \ \  \|\  \   
 \ \   __  \   \ \    / / \ \   ____\ \   __  \ \   _  _\  
  \ \  \ \  \   \/  /  /   \ \  \___|\ \  \ \  \ \  \\  \| 
   \ \__\ \__\__/  / /      \ \__\    \ \__\ \__\ \__\\ _\ 
    \|__|\|__|\___/ /        \|__|     \|__|\|__|\|__|\|__|
             \|___|/                                                                                   

Building archive...
There was an error during building. Try `dotnet build` and resolve any errors before publishing.
Your source code is available in ./Testfunction. Things to try:
- Update the hypar.json and run 'hypar init' to customize your function.
- Run 'hypar publish' to deploy new versions of your function to Hypar.
```
And running `dotnet build` fails as demoe'd below:
```console
~/ dotnet build
Microsoft (R) Build Engine version 16.1.76+g14b0a930a7 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 280.35 ms for /home/antoine/learning/dotnet/hypar/Testfunction/src/Testfunction.csproj.
  Restore completed in 330.48 ms for /home/antoine/learning/dotnet/hypar/Testfunction/test/Testfunction.tests.csproj.
Function.g.cs(17,11): error CS0305: Using the generic type 'IModelStore<TArgs>' requires 1 type arguments [/home/antoine/learning/dotnet/hypar/Testfunction/src/Testfunction.csproj]

Build FAILED.

Function.g.cs(17,11): error CS0305: Using the generic type 'IModelStore<TArgs>' requires 1 type arguments [/home/antoine/learning/dotnet/hypar/Testfunction/src/Testfunction.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:02.26
```

**Comment by AntoineDao** [comment]
Scratch that, I was using an old version of Hypar. I updated from `0.2.14` to `0.3.3` and it all worked on it's own like magic. This is awesome!! :smile:

**Comment by ikeough** [comment]
Thanks! We were just made aware of the global.json solution for developers who have multiple versions of .net core installed. We’ll be adding that to our bootstrapping capabilities to reduce confusion. Please let us know if you have further questions or feedback. Happy building!

**Comment by AntoineDao** [comment]
Is there a slack channel or some forum to discuss things that aren't explicitly bugs or features but just general `What am I doing?` or `What's coming up feature wise?`

**Comment by ikeough** [comment]
There is not, but you're not the first to ask. I recommend following notifications from this repo. We are going to add feature request issues as we develop the roadmap so that you can see and comment on upcoming developments.
